# Generated by Django 5.1.6 on 2025-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
