# Generated by Django 5.1.6 on 2025-03-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_version', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_version.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_version.user_profile')),
            ],
        ),
    ]
