# Generated by Django 5.1.6 on 2025-03-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_version', '0005_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to='first_version.user_profile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_name', to='first_version.posts'),
        ),
    ]
