# Generated by Django 5.1.6 on 2025-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_version', '0007_alter_comments_name_alter_comments_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='first_version.user_profile'),
        ),
    ]
