# Generated by Django 5.1.6 on 2025-03-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_version', '0008_user_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_version.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_version.user_profile')),
            ],
        ),
    ]
